services:
  postgres:
    image: postgres:15
    container_name: postgres_voice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audio_assistant
    ports:
      - "5432:5432"
    networks:
      - kafka_net
  redisearch:
    image: redislabs/redisearch:latest
    container_name: redisearch
    ports:
      - "6380:6379"
    networks:
      - kafka_net
  minio:
    image: minio/minio
    container_name: minio_voice
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka_voice
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    networks:
      - kafka_net

networks:
  kafka_net:
    driver: bridge

volumes:
    minio_data:
